apiVersion: v1
data:
  access_key_id: bWluaW8=
  access_key_secret: bWluaW8xMjM=
  bucket: dGVtcG8tZGF0YQ==
  endpoint: aHR0cDovL21pbmlvOjkwMDA=
kind: Secret
metadata:
  name: my-storage-secret
  namespace: tracing-system
type: Opaque
